CREATE TABLE property
(
	id INT NOT NULL AUTO_INCREMENT,
	property_name VARCHAR(100) NOT NULL,
	address VARCHAR(100) NOT NULL,
	tel1 VARCHAR(16) NOT NULL,
	email VARCHAR(100),
	detail1 VARCHAR(500),
	created DATETIME NOT NULL,
	PRIMARY KEY(id)
);
